---
- hosts: all
  user: ansible
  become: true
  connection: ssh
  tasks: 
    - name: Copying files
      copy:
        src: angular
        dest: /home/ansible
    - name: Run the docker Compose stack
      command: docker-compose -f /home/ansible/angular/compose.yaml up -d

